PFE_Project/PFE_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('',include("Patient.urls")),
    path('',include("authentication.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# handler404 = "PFE_Project.views.page_not_found_view"


PFE_Project/Patient/urls.py
from django.urls import URLPattern, path
from . import views
from .models import *

urlpatterns=[
    #---------------------------------------------------Générale------------------------------------------------------
    path('', views.index, name='home'),
    path('getUser/<str:email>', views.getUser, name="GetUser"),
    path('delImg/<int:id>', views.deleteImg, name="DelImg"),

    #---------------------------------------------------Patient------------------------------------------------------
    path('chercheCabinet/', views.search, name="cherCabinet"),
    path('Acceuil/', views.indexP, name="H_patient"),
    path('P_profil/', views.getP_Profil, name="profil_patient"),
    path('updateP_Profil/', views.updateP_Profil, name="update_profil_patient"),
    path('GetRV/<int:id>', views.getRV, name="GetListRV"),
    path('prendreRV/', views.prendRV, name="PrendRV"),
    path('ProfilD/<int:id>', views.ProfilD, name="ProfilD"),
    path('deleteRV/', views.deleteRV, name="DeleteRV"),
    path('Bookmark/<int:id>', views.bookmark, name="Bookmark"),
    path('writeComment/<int:id>', views.writeComment, name="Comment"),
    path('FavoriteDoc/', views.GetListFav, name="FavDoc"),
    path('FilterSearch/', views.SFilter, name="FilterSearch"),

    #---------------------------------------------------Doctor------------------------------------------------------
    path('AcceuilD/', views.indexD, name="H_doctor"),
    path('D_profil/', views.getD_Profil, name="profile_doctor"),
    path('updateD_Profil/', views.updateD_Profil, name="update_profil_doctor"),
    path('getTimingSchedual/', views.get_TimingSchedule, name="GetTimingSchedual"),
    path('addTimingSchedual/', views.add_TimingSchedule, name="AddTimingSchedual"),
    path('DelTimingSchedual/<int:id>', views.del_TimingSchedule, name="DelTimingSchedual"),
    path('DelTimingSchedual/', views.upd_TimingSchedule, name="UpdTimingSchedual"),
    path('GetPaitentList/', views.get_patient_list, name="GetPatientList"),
    path('GetRVList/', views.getListRV, name="GetListRV"),
    path('GetD_RVList/', views.getD_RD, name="D_RV_LIST"),
    path('annulerRV/', views.annulerRV, name="AnnulerRDV"),
    path('Dashboard/', views.getDashboard, name="Dashboard"),
    path('LibererJournee/', views.Liberer, name="LibererJournee"),
    path('GetAvis/', views.GetAvis, name="GetAvis"),

    #---------------------------------------------------Admin------------------------------------------------------
    path('A_panel/', views.index_admin, name="H_admin"),
    path('A_patients/', views.getPatientsA, name="PatientsAdmin"),
    path('A_doctors/', views.getDoctorsA, name="DoctorsAdmin"),
    path('A_specialites/', views.getspecialitesA, name="specialitesAdmin"),
    path('Add_specialites/', views.addSpecialite, name="AddSpecialite"),
    path('edit_specialites/', views.editSpecialite, name="EditSpecialite"),
    path('del_specialites/', views.delSpecialite, name="DeltSpecialite"),
    path('ClearRDV/', views.Clear, name="ClearRDV")
]

PFE_Project/Patient/models.py
from django.db import models
import datetime

class specialite(models.Model):
   specialite = models.CharField(max_length=400)
   def __str__(self):
        return self.specialite

class wilaya(models.Model):
    wilaya = models.CharField(max_length=20)
    def __str__(self):
        return self.wilaya

class commune(models.Model):
    commune = models.CharField(max_length=20)
    wilaya = models.ForeignKey(wilaya, on_delete=models.CASCADE)
    def __str__(self):
        return self.commune

blood_type = (("A+","A+"),("A-","A-"),("B+","B+"),("B-","B-"),("AB+","AB+"),("AB-","AB-"),("O+","O+"),("O-","O-"))
genre = (("female","female"),("male","male"))
class Medecin(models.Model):
    img_medecin = models.ImageField(null=True, upload_to='medecin', blank=True)
    nom_medecin = models.CharField(null=True, blank=True, max_length=20)
    prenom_medecin = models.CharField(null=True, blank=True, max_length=20)
    genre = models.CharField(max_length=10, choices=genre, null=True, blank=True)
    date_naiss = models.DateField(null=True, blank=True)
    biographie = models.TextField(null=True, blank=True)
    # rempalçant = models.BooleanField(default=False)
    googlemaps_iframe = models.CharField(max_length=1000, blank=True, null=True)
    email = models.EmailField(unique=True, blank=True, null=True)
    NomCabinet = models.CharField(max_length=60, unique=True, blank=True, null=True)
    telephone = models.PositiveBigIntegerField(blank=True, null=True)
    addresse = models.CharField(max_length=60, null=True, blank=True)
    specialite = models.ForeignKey(specialite, on_delete=models.CASCADE, null=True, blank=True)
    img1 = models.ImageField(null=True, upload_to='cabinet', blank=True, default="anonymous_clinic.jpg")
    img2 = models.ImageField(null=True, upload_to='cabinet', blank=True, default="anonymous_clinic.jpg")
    img3 = models.ImageField(null=True, upload_to='cabinet', blank=True, default="anonymous_clinic.jpg")
    wilaya = models.ForeignKey(wilaya, on_delete=models.CASCADE, null=True, blank=True)
    commune = models.ForeignKey(commune, on_delete=models.CASCADE, null=True, blank=True)
    rating = models.IntegerField(default=0.0, null=True, blank=True)
    Date_signIn = models.DateField(null=True, blank=True, default=datetime.datetime.now().date())
    def __str__(self):
       return self.email
    def changeFormat(self):
        return self.date_naiss.strftime("%m-%d-%Y") 

class Patient(models.Model):
    img_patient =  models.ImageField(null=True, upload_to='patient', blank=True)
    nomPatient = models.CharField(max_length=20, null=True, blank=True)
    prenomPatient = models.CharField(max_length=20, null=True, blank=True)
    date_naiss = models.DateField(null=True, blank=True)
    blood = models.CharField(null=True, blank=True, choices=blood_type, max_length=4)
    genre = models.CharField(max_length=10, choices=genre, null=True, blank=True)
    emailPatient = models.EmailField(unique=True)
    telephone = models.PositiveBigIntegerField(blank=True, null=True)
    Address = models.CharField(max_length=60, blank=True, null=True)
    commune = models.ForeignKey(commune, null=True, blank=True, on_delete=models.CASCADE)
    wilaya = models.ForeignKey(wilaya, null=True, blank=True, on_delete=models.CASCADE)
    Date_signIn = models.DateField(null=True, blank=True, default=datetime.datetime.now().date())
    def __str__(self):
        return self.emailPatient
    def changeFormat(self):
        return self.date_naiss.strftime("%m-%d-%Y")
    def age(self):
        current_year = datetime.datetime.now().year
        return current_year-self.date_naiss.year

class Anonymous(models.Model):
    nom = models.CharField(max_length=20)
    prenom = models.CharField(max_length=20)
    date_naiss = models.DateField(null=True, blank=True)

class Motif(models.Model):
    nomMotif = models.CharField(max_length=60, null=True, blank=True)
    def __str__(self):
        return self.nomMotif

duree = ((15,15),(30,30),(45,45),(60,60),(90,90))
jours = (("Dimenche","Dimenche"),("Lundi","Lundi"),
("Mardi","Mardi"),("Mercredi","Mercredi"),
("Jeudi","Jeudi"),("Vendredi","Vendredi"),
("Samedi","Samedi"))
class type_consultation(models.Model):
    motif = models.ForeignKey(Motif, on_delete=models.CASCADE)
    medecin = models.ForeignKey(Medecin, on_delete=models.CASCADE)
    duree = models.IntegerField(choices=duree)
    prix = models.PositiveIntegerField()
    j = models.CharField(max_length=10, choices=jours, null=True, blank=True)
    start = models.TimeField(default="0:0")
    end = models.TimeField(default="0:0")
    def __str__(self):
        return self.j+' '+self.motif.nomMotif
    def getDay(self):
        days = {
            "Lundi" : 0,
            "Mardi" : 1,
            "Mercredi" : 2,
            "Jeudi" : 3,
            "Vendredi" : 4,
            "Samedi" : 5,
            "Dimenche" : 6
        }
        return days.get(self.j)

class RV(models.Model):
    Date = models.DateField(null=True, blank=True)
    type = models.ForeignKey(type_consultation, on_delete=models.CASCADE, null=True, blank=True)
    heure = models.TimeField(default="0:0")
    duree = models.PositiveIntegerField(null=True, blank=True)
    medecin = models.ForeignKey(Medecin, on_delete=models.CASCADE, null=True, blank=True)
    Patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True)
    def french_Date(self):
        year = self.Date.year
        month = self.Date.month
        day = self.Date.day
        return str(day)+"-"+str(month)+"-"+str(year)
    def french_time(self):
        return self.heure.strftime("%H:%M:%S")

status = (("completé","completé"),("annulé","annulé"),("confirmé","confirmé"))
class RV_valide(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    medecin = models.ForeignKey(Medecin, on_delete=models.CASCADE)
    dateRV = models.DateField()
    heure = models.TimeField(default="0:0")
    type_consultation = models.ForeignKey(type_consultation, on_delete=models.CASCADE)
    nom_payer = models.CharField(max_length=20, null=True, blank=True)
    prenom_payer = models.CharField(max_length=20, null=True, blank=True)
    num_carte = models.CharField(max_length=20, null=True, blank=True)
    status = models.CharField(max_length=15, choices=status)
    pour_anonymous = models.BooleanField(default=False)
    anonymous_patient = models.ForeignKey(Anonymous, on_delete=models.CASCADE, null=True, blank=True)
    def french_Date(self):
        year = self.dateRV.year
        month = self.dateRV.month
        months = ["Jan", "Fév", "Mars", "Avr", "Mai", "Juin", "Jui", "Aôut", "Sep","Oct", "Nov", "Dec"]
        day = self.dateRV.day
        return str(day)+" "+str(months[month-1])+" "+str(year)
    def french_time(self):
        return self.heure.strftime("%H:%M:%S")
    
    def day_name(self):
        days = ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"]
        return str(days[self.dateRV.weekday()])
        
class Avi(models.Model):
    cabinet = models.ForeignKey(Medecin, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    content = models.TextField()
    rating = models.IntegerField(default=0)
    date = models.DateField(null=True, blank=True)

    def __str__(self):
        return 'Commentaire '+self.cabinet.NomCabinet+'--'+self.patient.nomPatient

    def french_Date(self):
        year = self.date.year
        month = self.date.month
        months = ["Jan", "Fév", "Mars", "Avr", "Mai", "Juin", "Jui", "Aôut", "Sep","Oct", "Nov", "Dec"]
        day = self.date.day
        return str(day)+" "+str(months[month-1])+" "+str(year)

class Notification(models.Model):
    user = models.EmailField(null=True, blank=True)
    Date = models.DateTimeField(null=True, blank=True)
    content = models.CharField(max_length=200, null=True, blank=True)
    sender = models.EmailField(null=True, blank=True)
    new = models.BooleanField(default=True)
    def french_Date(self):
        year = self.Date.year
        month = self.Date.month
        day = self.Date.day
        return str(day)+"-"+str(month)+"-"+str(year)
    def __str__(self):
        return self.user

class MedecinFavori(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True)
    medecin = models.ForeignKey(Medecin, on_delete=models.CASCADE, null=True, blank=True)
    

PFE_Project/Patient/forms.py
from django import forms
from .models import *

class profil_P_form(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('img_patient','nomPatient',
        'prenomPatient','date_naiss','blood',
        'genre','telephone','Address', 'commune',
        'wilaya')

class profil_D_form(forms.ModelForm):
    class Meta:
        model = Medecin
        fields = '__all__'
        
class Motif_form(forms.ModelForm):
    class Meta:
        model = type_consultation
        fields = '__all__'
        
class specialiteForm(forms.ModelForm):
    class Meta:
        model = specialite
        fields = '__all__'

PFE_Project/templates/A/Doctors.html
{%extends 'A/base.html'%}
{%load static%}

{%block sideBar%}
    <li> 
        <a href="{%url 'H_admin'%}"><i class="fas fa-home" style="font-size: 20px;"></i> <span>Dashboard</span></a>
    </li>
    <li> 
        <a href="{%url 'specialitesAdmin'%}"><i class="fas fa-users" style="font-size: 20px;"></i> <span>Specialities</span></a>
    </li>
    <li  class="active"> 
        <a href="{%url 'DoctorsAdmin'%}"><i class="fas fa-user-plus" style="font-size: 20px;"></i> <span>Médecins</span></a>
    </li>
    <li> 
        <a href="{%url 'PatientsAdmin'%}"><i class="fas fa-user" style="font-size: 20px;"></i> <span>Patients</span></a>
    </li>
    <li> 
        <a href="{%url 'Logout'%}"><i class="fas fa-sign-out-alt" style="font-size: 20px;"></i> <span>Logout</span></a>
    </li>
{%endblock%}

{%block content%}
    <div class="page-wrapper">
        <div class="content container-fluid">
        
            <!-- Page Header -->
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-12">
                        <h3 class="page-title">List des Médecins</h3>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{%url 'H_admin'%}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Médecins</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /Page Header -->
            
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="datatable table table-hover table-center mb-0">
                                    <thead>
                                        <tr>
                                            <th>Nom Médecin</th>
                                            <th>Specialité</th>
                                            <th>Date inscription</th>
                                            <!-- <th>Account Status</th> -->
                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {%for doctor in doctors%}
                                        <tr>
                                            <td>
                                                <h2 class="table-avatar">
                                                    <a href="#" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{doctor.img_medecin.url}}" alt="User Image"></a>
                                                    <a href="#">{{doctor.NomCabinet}}</a>
                                                </h2>
                                            </td>
                                            <td>{{doctor.specialite}}</td>
                                            
                                            <td>{{doctor.Date_signIn}}</td>
                                            
                                            <!-- <td>
                                                <div class="status-toggle">
                                                    <input type="checkbox" id="status_1" class="check" checked>
                                                    <label for="status_1" class="checktoggle">checkbox</label>
                                                </div>
                                            </td> -->
                                        </tr>
                                        {%endfor%}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>			
            </div>
            
        </div>			
    </div>
{%endblock%}

{%block scripts%}{%endblock%}

PFE_Project/templates/A/Patients.html
{%extends 'A/base.html'%}
{%load static%}

{%block sideBar%} 
	<li> 
		<a href="{%url 'H_admin'%}"><i class="fas fa-home" style="font-size: 20px;"></i> <span>Dashboard</span></a>
	</li>
	<li> 
		<a href="{%url 'specialitesAdmin'%}"><i class="fas fa-users" style="font-size: 20px;"></i> <span>Specialities</span></a>
	</li>
	<li> 
		<a href="{%url 'DoctorsAdmin'%}"><i class="fas fa-user-plus" style="font-size: 20px;"></i> <span>Médecins</span></a>
	</li>
	<li class="active"> 
		<a href="{%url 'PatientsAdmin'%}"><i class="fas fa-user" style="font-size: 20px;"></i> <span>Patients</span></a>
	</li>
	<li> 
		<a href="{%url 'Logout'%}"><i class="fas fa-sign-out-alt" style="font-size: 20px;"></i> <span>Logout</span></a>
	</li>
{%endblock%}

{%block content%}
    <div class="page-wrapper">
        <div class="content container-fluid">
        
            <!-- Page Header -->
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-12">
                        <h3 class="page-title">List des Patients</h3>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{%url 'H_admin'%}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Patient</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /Page Header -->
            
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <div class="table-responsive">
                                <table class="datatable table table-hover table-center mb-0">
                                    <thead>
                                        <tr>
                                            <th>Nom Patient</th>
                                            <th>Age</th>
                                            <th>Address</th>
                                            <th>Phone</th>
                                            <th>Email</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {%for patient in patients%}
                                        <tr>
                                            <td>
                                                <h2 class="table-avatar">
                                                    <a href="#" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{patient.img_patient.url}}" alt="User Image"></a>
                                                    <a href="#">{{patient.nomPatient}} {{patient.prenomPatient}}</a>
                                                </h2>
                                            </td>
                                            <td>{{patient.age}}</td>
                                            <td>{{patient.Address}}, {{patient.commune}}, {{patient.wilaya}}</td>
                                            <td>{{patient.telephone}}</td>
                                            <td>{{patient.emailPatient}}</td>
                                        </tr>
                                        {%endfor%}
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>			
            </div>
            
        </div>			
    </div>
{%endblock%}

PFE_Project/templates/A/specialites.html
{%extends 'A/base.html'%}
{%load static%}

{%block sideBar%}
    <li> 
        <a href="{%url 'H_admin'%}"><i class="fas fa-home" style="font-size: 20px;"></i> <span>Dashboard</span></a>
    </li>
    <li  class="active"> 
        <a href="{%url 'specialitesAdmin'%}"><i class="fas fa-users" style="font-size: 20px;"></i> <span>Specialities</span></a>
    </li>
    <li> 
        <a href="{%url 'DoctorsAdmin'%}"><i class="fas fa-user-plus" style="font-size: 20px;"></i> <span>Médecins</span></a>
    </li>
    <li> 
        <a href="{%url 'PatientsAdmin'%}"><i class="fas fa-user" style="font-size: 20px;"></i> <span>Patients</span></a>
    </li>
    <li> 
        <a href="{%url 'Logout'%}"><i class="fas fa-sign-out-alt" style="font-size: 20px;"></i> <span>Logout</span></a>
    </li>
{%endblock%}

{%block content%}
<div class="page-wrapper">
    <div class="content container-fluid">
    
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-7 col-auto">
                    <h3 class="page-title">Specialities</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Specialities</li>
                    </ul>
                </div>
                <div class="col-sm-5 col">
                    <a href="#Add_Specialities_details" data-toggle="modal" class="btn btn-primary float-right mt-2">Ajouter</a>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="datatable table table-hover table-center mb-0">
                                <thead>
                                    <tr>
                                        <th>Specialities</th>
                                        <th class="text-right">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {%for specialite in specialites%}
                                    <tr>
                                        <td>
                                            <h2 class="table-avatar">
                                                <!-- <a href="#" class="avatar avatar-sm mr-2">
                                                    <img class="avatar-img" src="assets/img/specialities/specialities-01.png" alt="Speciality">
                                                </a> -->
                                                <a href="#">{{specialite.specialite}}</a>
                                            </h2>
                                        </td>
                                    
                                        <td class="text-right">
                                            <div class="actions">
                                                <a class="btn btn-sm bg-success-light edit_specialite" onclick="setSpecialite(event)" data-toggle="modal" data-id="{{specialite.id}}" data-value="{{specialite.specialite}}" href="#edit_specialities_details">
                                                    <i class="fe fe-pencil"></i> Modifier
                                                </a>
                                                <a  data-toggle="modal" href="#delete_modal" onclick="setIDspecialite(event)" data-id="{{specialite.id}}" class="btn btn-sm bg-danger-light">
                                                    <i class="fe fe-trash"></i> Supprimer
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    {%endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>			
        </div>
    </div>			
</div>
<!-- /Page Wrapper -->


<!-- Add Modal -->
<div class="modal fade" id="Add_Specialities_details" aria-hidden="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document" >
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Specialities</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{%url 'AddSpecialite'%}">
                    {% csrf_token %}
                    <div class="row form-row">
                        <div class="col-12 col-sm-12">
                            <div class="form-group">
                                <label>Specialities</label>
                                <input type="text" class="form-control" name="specialite">
                            </div>
                        </div>
                        <!-- <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label>Image</label>
                                <input type="file"  class="form-control">
                            </div>
                        </div> -->
                        
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Créer spécialité</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- /ADD Modal -->

<!-- Edit Details Modal -->
<div class="modal fade" id="edit_specialities_details" aria-hidden="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document" >
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modifier Specialities</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{%url 'EditSpecialite'%}">
                    {% csrf_token %}
                    <div class="row form-row">
                        <div class="col-12 col-sm-12">
                            <div class="form-group">
                                <label>Specialities</label>
                                <input id="specialite" type="text" class="form-control" value=""  name="specialite">
                            </div>
                            <div class="form-group">
                                <input id="id_specialite" style="display: none;" type="text" class="form-control" value=""  name="id">
                            </div>
                        </div>
                        <!-- <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label>Image</label>
                                <input type="file"  class="form-control">
                            </div>
                        </div> -->
                        
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Sauvgarder</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- /Edit Details Modal -->

<!-- Delete Modal -->
<div class="modal fade" id="delete_modal" aria-hidden="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document" >
        <div class="modal-content">
        <!--	<div class="modal-header">
                <h5 class="modal-title">Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>-->
            <div class="modal-body">

                <form method="POST" action="{%url 'DeltSpecialite'%}">
                    {% csrf_token %}
                    <div class="form-content p-2">
                        <div class="form-group">
                            <input id="id_specialite_del" style="display: none;" type="text" class="form-control" value=""  name="id">
                        </div>
                        <h4 class="modal-title">Delete</h4>
                        <p class="mb-4">Vous êtes sure que vous voulez supprimer cette spécialité?</p>
                        <button type="submit" class="btn btn-primary">Supprimer </button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>
                    </div>
                </form>
                
            </div>
        </div>
    </div>
</div>
<!-- /Delete Modal -->
{%endblock%}

{%block scripts%}
    <script>
        function setSpecialite(event){
            document.getElementById("specialite").value = event.target.getAttribute('data-value');
            document.getElementById("id_specialite").value = event.target.getAttribute('data-id');
        }

        function setIDspecialite(event){
            document.getElementById("id_specialite_del").value = event.target.getAttribute('data-id');
        }
    </script>
{%endblock%}